//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novo.Docx.Cli.CommandLineValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novo.Docx.Cli.CommandLineValidation.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not allowed in a path: {0}.
        /// </summary>
        internal static string CharacterNotAllowedInPath {
            get {
                return ResourceManager.GetString("CharacterNotAllowedInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; only accepts a single argument but {1} were provided..
        /// </summary>
        internal static string CommandAcceptsOnlyOneArgument {
            get {
                return ResourceManager.GetString("CommandAcceptsOnlyOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; expects no more than {1} arguments, but {2} were provided..
        /// </summary>
        internal static string CommandExpectsFewerArguments {
            get {
                return ResourceManager.GetString("CommandExpectsFewerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist: {0}.
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading response file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorReadingResponseFile {
            get {
                return ResourceManager.GetString("ErrorReadingResponseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist: {0}.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or directory does not exist: {0}.
        /// </summary>
        internal static string FileOrDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("FileOrDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template pattern &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidTemplateError {
            get {
                return ResourceManager.GetString("InvalidTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last argument &apos;{0}&apos; accepts multiple values. No more argument can be added..
        /// </summary>
        internal static string LastArgumentMultiValueError {
            get {
                return ResourceManager.GetString("LastArgumentMultiValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any extra options that should be passed to MSBuild. See &apos;dotnet msbuild -h&apos; for available options..
        /// </summary>
        internal static string MSBuildAdditionalArgsHelpText {
            get {
                return ResourceManager.GetString("MSBuildAdditionalArgsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; only accepts a single argument but {1} were provided..
        /// </summary>
        internal static string OptionAcceptsOnlyOneArgument {
            get {
                return ResourceManager.GetString("OptionAcceptsOnlyOneArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; expects no more than {1} arguments, but {2} were provided..
        /// </summary>
        internal static string OptionExpectsFewerArguments {
            get {
                return ResourceManager.GetString("OptionExpectsFewerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required value for option &apos;{0}&apos; was not provided..
        /// </summary>
        internal static string OptionRequiresSingleValueWhichIsMissing {
            get {
                return ResourceManager.GetString("OptionRequiresSingleValueWhichIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for command: {0}.
        /// </summary>
        internal static string RequiredArgumentMissingForCommand {
            get {
                return ResourceManager.GetString("RequiredArgumentMissingForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for option: {0}.
        /// </summary>
        internal static string RequiredArgumentMissingForOption {
            get {
                return ResourceManager.GetString("RequiredArgumentMissingForOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for command: {0}.
        /// </summary>
        internal static string RequiredCommandArgumentMissing {
            get {
                return ResourceManager.GetString("RequiredCommandArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required command was not provided..
        /// </summary>
        internal static string RequiredCommandWasNotProvided {
            get {
                return ResourceManager.GetString("RequiredCommandWasNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required argument missing for option: {0}.
        /// </summary>
        internal static string RequiredOptionArgumentMissing {
            get {
                return ResourceManager.GetString("RequiredOptionArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file not found &apos;{0}&apos;.
        /// </summary>
        internal static string ResponseFileNotFound {
            get {
                return ResourceManager.GetString("ResponseFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response file &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string ResponseFileNotFoundError {
            get {
                return ResourceManager.GetString("ResponseFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command line help..
        /// </summary>
        internal static string ShowHelpInfo {
            get {
                return ResourceManager.GetString("ShowHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify --{0} for a list of available options and commands..
        /// </summary>
        internal static string ShowHintInfo {
            get {
                return ResourceManager.GetString("ShowHintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show version information.
        /// </summary>
        internal static string ShowVersionInfo {
            get {
                return ResourceManager.GetString("ShowVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized {0} &apos;{1}&apos;.
        /// </summary>
        internal static string UnexpectedArgumentError {
            get {
                return ResourceManager.GetString("UnexpectedArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value &apos;{0}&apos; for option &apos;{1}&apos;.
        /// </summary>
        internal static string UnexpectedValueForOptionError {
            get {
                return ResourceManager.GetString("UnexpectedValueForOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; not recognized. Must be one of: {1}.
        /// </summary>
        internal static string UnrecognizedArgument {
            get {
                return ResourceManager.GetString("UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command or argument &apos;{0}&apos;.
        /// </summary>
        internal static string UnrecognizedCommandOrArgument {
            get {
                return ResourceManager.GetString("UnrecognizedCommandOrArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string UsageArgumentsHeader {
            get {
                return ResourceManager.GetString("UsageArgumentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [arguments].
        /// </summary>
        internal static string UsageArgumentsToken {
            get {
                return ResourceManager.GetString("UsageArgumentsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [[--] &lt;additional arguments&gt;...]].
        /// </summary>
        internal static string UsageCommandAdditionalArgs {
            get {
                return ResourceManager.GetString("UsageCommandAdditionalArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [args].
        /// </summary>
        internal static string UsageCommandArgs {
            get {
                return ResourceManager.GetString("UsageCommandArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Arguments:.
        /// </summary>
        internal static string UsageCommandsAdditionalArgsHeader {
            get {
                return ResourceManager.GetString("UsageCommandsAdditionalArgsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;{0} [command] --help&quot; for more information about a command..
        /// </summary>
        internal static string UsageCommandsDetailHelp {
            get {
                return ResourceManager.GetString("UsageCommandsDetailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands:.
        /// </summary>
        internal static string UsageCommandsHeader {
            get {
                return ResourceManager.GetString("UsageCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [command].
        /// </summary>
        internal static string UsageCommandToken {
            get {
                return ResourceManager.GetString("UsageCommandToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string UsageHeader {
            get {
                return ResourceManager.GetString("UsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string UsageOptionsHeader {
            get {
                return ResourceManager.GetString("UsageOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [options].
        /// </summary>
        internal static string UsageOptionsToken {
            get {
                return ResourceManager.GetString("UsageOptionsToken", resourceCulture);
            }
        }
    }
}
